services:
  db:
    container_name: blog_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    container_name: blog_backend
    restart: always
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - "db"
